### ISSUE TITLE
add a log in page

### ISSUE THREAD

**Issue by thakuraman24** [thakuraman24/CO-OLX-PBL#1]
![create-login-page-with-html-css-sample](https://github.com/thakuraman24/CO-OLX-PBL/assets/97963364/1da60b9b-1d1d-4c99-a77d-befce44e9fb8)

**Comment by ramprataptomar** [comment]
please assign this issue to me

**Comment by thakuraman24** [comment]
thankyou for working on this .

**Comment by thakuraman24** [comment]
closed
